// Online Java Compiler
// Use this editor to write, compile and run your Java code online
/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
By starting with 1 and 2, 
the first 10 terms will be:1, 2, 3, 5, 8, 13, 21, 34, 55, 89...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/
class Kiah_Farrington_Q2 {
    public static void main(String[] args) {
        int prev = 1;
        int temp = 2;
        int next = 0;
        int evenSum = 0;
        while(temp < 4_000_000)
        {
            // checks if even num, if so adds to sum
           if(temp % 2 == 0){
               evenSum += temp;
           }
           //moves along the Fibonacci sequence
           next = prev + temp;
           prev = temp;
           temp = next;
        }
        System.out.print("the sum of even numbers in the Fibonacci sequence under 4 million is:\n" + evenSum);
    }
}